version: "2.1"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    env_file:
      - default.env
    volumes:
      - /home/jonas/docker/appdata/bazarr:/config
      - /mnt/storage/files/movies:/movies
      - /mnt/storage/files/series:/tv
    ports:
      - 6767:6767
    restart: always
