version: "2.1"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    env_file:
      - default.env
    volumes:
      - /home/jonas/docker/appdata/bazarr:/config
      #- </path/to/movies>:/movies
      #- </path/to/tv>:/tv
    ports:
      - 6767:6767
    restart: always