version: "2.1"
services:
  emby:
    image: linuxserver/emby
    container_name: emby
    env_file:
      - default.env
    volumes:
      - /home/jonas/docker/appdata/emby:/config
     # - /path/to/tvshows:/data/tvshows
     # - /path/to/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped