version: "2.1"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/jonas/docker/appdata/grafana:/var/lib/grafana
     # - /path/to/tvshows:/data/tvshows
     # - /path/to/movies:/data/movies
    ports:
      - 3000:3000
    restart: unless-stopped