version: "2.1"
services:
  influxdb:
    image: influxdb/influxdb
    container_name: influxdb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/jonas/docker/appdata/influxdb:/var/lib/influxdb
    ports:
      - 8083:8083
      - 8086:8086
    restart: unless-stopped