version: "2.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    env_file:
      - default.env
    volumes:
      - /home/jonas/docker/appdata/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
