version: "2.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/jonas/docker/appdata/jackett:/config
      #- /mnt/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped