version: "2.1"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    env_file:
      - default.env
    volumes:
      - /home/jonas/docker/appdata/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
