version: "2.1"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/jonas/docker/appdata/ombi:/config
      #- /mnt/downloads:/downloads
    ports:
      - 3579:3579
    restart: unless-stopped