version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/jonas/docker/appdata/plex:/config
      - /tmp/transcode/plex:/transcode
      #- /mnt/downloads:/movies
      #- /mnt/downloads:/tv
    network_mode: host
    restart: unless-stopped