version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    env_file:
      - default.env
    volumes:
      - /home/jonas/docker/appdata/radarr:/config
      #- /mnt/downloads:/movies
      #- /mnt/downloads:/downloads
    ports:
      - 7878:7878 
    restart: unless-stopped