version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/jonas/docker/appdata/sonarr:/config
      #- /mnt/downloads:/media
      #- /mnt/downloads:/downloads
    ports:
      - 8989:8989 
    restart: unless-stopped