version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    env_file:
      - default.env
    volumes:
      - /home/jonas/docker/appdata/sonarr:/config
      #- /mnt/downloads:/media
      #- /mnt/downloads:/downloads
    ports:
      - 8989:8989 
    restart: unless-stopped