version: "2.1"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - EMAIL=lundbergjonas96@gmail.com
      - URL=hejsan.xyz
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - /home/jonas/docker/appdata/swag:/config
    ports:
      - 8080:80
      - 4433:443
    restart: unless-stopped