version: "2.1"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/jonas/docker/appdata/tautulli:/config
      - "/home/jonas/docker/appdat/plex/Library/Application Support/Plex Media Server/Logs/":/logs
    ports:
      - 8181:8181
    restart: unless-stopped