version: "3.7"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always
