version: "3.7"
services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    network_mode: host
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/homeassistant:/config
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
