version: "3.7"
services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/homeassistant:/config
    restart: always
  zwave:
    image: zwavejs/zwavejs2mqtt:latest
    container_name: zwave
#    network_mode: service:vpn
    env_file:
      - ../default.env
    environment:
      - SESSION_SECRET=ccd3fc23c7e9dafc5e8b8fdd5a621dab
    volumes:
      - /home/jonas/docker/appdata/zwave:/usr/src/app/store
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    ports:
      - 8091:8091
#      - 3000:3000
