version: "2.1"
services:
  influxdb:
    image: influxdb/influxdb
    container_name: influxdb
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/influxdb:/var/lib/influxdb
    ports:
      - 8083:8083
      - 8086:8086
    restart: always
