version: "3.7"
services:
  kitana:
    image: pannal/kitana
    container_name: kitana
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/kitana:/app/data
    ports:
      - 31337:31337
    restart: always
