version: "3.7"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/ombi:/config
    restart: always
