version: "3.7"
services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - ServerIP=192.168.1.4
      - DNSMASQ_LISTENING=all
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/pihole/pihole:/etc/pihole/
      - /home/jonas/docker/appdata/pihole/dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - 53:53
      - 67:67
      - 80:80
      - 443:443
    restart: always
