version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/plex:/config
      - /tmp/transcode/plex:/transcode
      - /mnt/storage/files/movies:/movies
      - /mnt/storage/files/series:/tv
    network_mode: host
    restart: always
