version: "3.7"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    environment:
      - EMAIL=josnase@gmail.com
      - URL=hejsan.xyz
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/swag:/config
    ports:
      - 8081:80
      - 4433:443
    restart: always
