version: "3.7"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/tautulli:/config
      - /home/jonas/docker/appdata/plex/Library/Application Support/Plex Media Server/Logs/:/logs
    ports:
      - 8181:8181
    restart: always
