version: "3.7"
services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:latest
    restart: always
    cap_add:
      - net_admin
    ports:
      - 9091:9091 #transmission 
      - 7878:7878 #radarr
      - 8989:8989 #sonarr 
      - 9117:9117 #jackett
      - 6767:6767 #bazarr
    environment:
      REGION: "sweden"
      VPNSP: "private internet access"
      PORT_FORWARDING: "on"
      #FIREWALL_OUTBOUND_SUBNETS: "192.168.1.0/24"
    env_file:
      - ../transmission.env
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/vpn/:/gluetun


  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: always
    network_mode: service:vpn
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/transmission/:/data
      - /mnt/storage/downloads/:/downloads
    restart: always



  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: service:vpn
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/radarr:/config
      - /mnt/storage/files/movies:/movies
      - /mnt/storage/downloads/complete/movies:/downloads/complete/movies
    restart: always



  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: service:vpn
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/sonarr:/config
      - /mnt/storage/files/series:/media
      - /mnt/storage/downloads/complete/series:/downloads/complete/series
    restart: always


  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: service:vpn
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/jackett:/config
    restart: always

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    network_mode: service:vpn
    env_file:
      - ../default.env
    volumes:
      - /home/jonas/docker/appdata/bazarr:/config
      - /mnt/storage/files/movies:/movies
      - /mnt/storage/files/series:/tv
    restart: always

